#!/usr/bin/env node
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { THEMES, pickTheme } = require('./themes');

const USERNAME = process.env.THM_USERNAME;
const OUTPUT_PATH = process.env.OUTPUT_PATH || 'assets/thm_badge.svg';
const THEME_INPUT = process.env.THEME || 'rotate';
const ACCENT_OVERRIDE = (process.env.ACCENT_COLOR || '').trim();

if (!USERNAME) {
  console.error('[thm-badge] FATAL: THM_USERNAME env var is required.');
  process.exit(1);
}

const FONT_MONO ="ui-monospace,'SF Mono','Menlo','Cascadia Code','Consolas','Liberation Mono',monospace";

function formatPoints(n) {
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(1).replace(/\.0$/, '') + 'M';
  if (n >= 10_000) return (n / 1_000).toFixed(1).replace(/\.0$/, '') + 'K';
  if (n >= 1_000) return n.toLocaleString('en-US');
  return String(n);
}

function levelToHex(n) {
  return '0x' + n.toString(16).toUpperCase();
}

function levelToTitle(n) {
  const titles = [
    'NEOPHYTE', 'APPRENTICE', 'PATHFINDER', 'SEEKER', 'VISIONARY',
    'VOYAGER', 'ADEPT', 'HACKER', 'MAGE', 'WIZARD',
    'MASTER', 'GURU', 'LEGEND', 'GUARDIAN', 'TITAN',
    'SAGE', 'VANGUARD', 'SHOGUN', 'ASCENDED', 'MYTHIC', 'GRANDMASTER',
  ];
  return titles[Math.min(n - 1, titles.length - 1)] || 'NEOPHYTE';
}

const CAPABILITY_PALETTES = {
  red:   { from: '#ff8a6b', to: '#e94e3a' },
  green: { from: '#c5cfff', to: '#5a7cff' },
};

function capabilityPalette(pov) {
  return CAPABILITY_PALETTES[pov] || CAPABILITY_PALETTES.red;
}

function escapeXml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function setOutput(name, value) {
  if (!process.env.GITHUB_OUTPUT) return;
  fs.appendFileSync(process.env.GITHUB_OUTPUT, `${name}=${value}\n`);
}

function buildSvg(data, theme, themeName) {
  const username = escapeXml(data.username);
  const levelHex = levelToHex(data.level);
  const rank = data.rank.toLocaleString('en-US');
  const topPct = data.topPercentage;
  const rooms = data.completedRoomsNumber;
  const badges = data.badgesNumber;
  const points = formatPoints(data.totalPoints);
  const league = escapeXml((data.leagueTier || 'unranked').toUpperCase());
  const updatedAt = new Date().toISOString().slice(0, 10);
  const cap = data.capabilityScore;
  const capValue = cap && Number.isFinite(cap.value) ? Math.round(cap.value) : null;
  const capPalette = capabilityPalette(cap && cap.pov);

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 180" width="640" height="180" role="img" aria-label="TryHackMe stats for ${username}">
  <title>TryHackMe — ${username} — Top ${topPct}% — Rank #${rank} — theme: ${themeName}</title>
  <desc>Auto-generated by KeizerSec/Tryhackme-Badge — updated ${updatedAt}</desc>
  <defs>
    <linearGradient id="bgGrad" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="${theme.bgFrom}"/>
      <stop offset="100%" stop-color="${theme.bgTo}"/>
    </linearGradient>
    <linearGradient id="rankGrad" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="${theme.accent}"/>
      <stop offset="100%" stop-color="${theme.accentSoft}"/>
    </linearGradient>
    <linearGradient id="accentGrad" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="${theme.accent}" stop-opacity="0"/>
      <stop offset="50%" stop-color="${theme.accent}" stop-opacity="0.6"/>
      <stop offset="100%" stop-color="${theme.accent}" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="capGrad" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="${capPalette.from}"/>
      <stop offset="100%" stop-color="${capPalette.to}"/>
    </linearGradient>
    <filter id="glow" x="-20%" y="-20%" width="140%" height="140%">
      <feGaussianBlur stdDeviation="1.4" result="b"/>
      <feMerge>
        <feMergeNode in="b"/>
        <feMergeNode in="SourceGraphic"/>
      </feMerge>
    </filter>
  </defs>

  <rect x="0.5" y="0.5" width="639" height="179" rx="14" ry="14" fill="url(#bgGrad)" stroke="${theme.border}" stroke-opacity="0.35" stroke-width="1"/>

  <path d="M 14,1 L 70,1 L 14,57 Z" fill="${theme.accent}" opacity="0.08"/>
  <path d="M 626,179 L 570,179 L 626,123 Z" fill="${theme.secondary}" opacity="0.08"/>

  <g transform="translate(28,18)">
    <rect x="0" y="0" width="84" height="18" rx="4" ry="4" fill="${theme.secondary}" fill-opacity="0.12" stroke="${theme.secondary}" stroke-opacity="0.5"/>
    <text x="42" y="13" fill="${theme.secondary}" font-family="${FONT_MONO}" font-size="10" font-weight="700" letter-spacing="2.5" text-anchor="middle">TRYHACKME</text>
  </g>

  <text x="28" y="68" fill="${theme.text}" font-family="${FONT_MONO}" font-size="30" font-weight="700">${username}</text>
  <text x="28" y="92" fill="${theme.muted}" font-family="${FONT_MONO}" font-size="11" font-weight="500" letter-spacing="1.2">[${levelHex}] ${levelToTitle(data.level)} · ${league} LEAGUE</text>
${capValue !== null ? `  <g transform="translate(280,80)">
    <rect x="6" y="0" width="6" height="6" rx="0.8" fill="url(#capGrad)" transform="rotate(45 9 3)"/>
    <rect x="0" y="6" width="6" height="6" rx="0.8" fill="url(#capGrad)" transform="rotate(45 3 9)"/>
    <rect x="12" y="6" width="6" height="6" rx="0.8" fill="url(#capGrad)" transform="rotate(45 15 9)"/>
    <rect x="6" y="12" width="6" height="6" rx="0.8" fill="url(#capGrad)" transform="rotate(45 9 15)"/>
    <text x="24" y="13" fill="${theme.text}" font-family="${FONT_MONO}" font-size="11" font-weight="700" letter-spacing="1.2">${capValue}</text>
    <text x="42" y="13" fill="${theme.muted}" font-family="${FONT_MONO}" font-size="11" font-weight="500" letter-spacing="1.2">CAPABILITY</text>
  </g>` : ''}

  <g transform="translate(612,18)">
    <rect x="-94" y="0" width="94" height="18" rx="4" ry="4" fill="${theme.accent}" fill-opacity="0.10" stroke="${theme.accent}" stroke-opacity="0.45"/>
    <text x="-47" y="13" fill="${theme.accent}" font-family="${FONT_MONO}" font-size="10" font-weight="700" letter-spacing="2.5" text-anchor="middle">WORLD RANK</text>
  </g>
  <text x="612" y="62" fill="url(#rankGrad)" font-family="${FONT_MONO}" font-size="28" font-weight="700" text-anchor="end" filter="url(#glow)">#${rank}</text>
  <text x="612" y="92" fill="${theme.accent}" fill-opacity="0.85" font-family="${FONT_MONO}" font-size="11" font-weight="600" letter-spacing="1.2" text-anchor="end">TOP ${topPct}% WORLDWIDE</text>

  <rect x="28" y="106" width="584" height="1" fill="url(#accentGrad)"/>

  <g font-family="${FONT_MONO}" text-anchor="middle">
    <text x="98"  y="142" fill="${theme.text}" font-size="24" font-weight="700">${rooms}</text>
    <text x="98"  y="161" fill="${theme.muted}" font-size="9"  font-weight="600" letter-spacing="2.2">ROOMS</text>

    <text x="246" y="142" fill="${theme.text}" font-size="24" font-weight="700">${badges}</text>
    <text x="246" y="161" fill="${theme.muted}" font-size="9"  font-weight="600" letter-spacing="2.2">BADGES</text>

    <text x="394" y="142" fill="${theme.text}" font-size="24" font-weight="700">${points}</text>
    <text x="394" y="161" fill="${theme.muted}" font-size="9"  font-weight="600" letter-spacing="2.2">POINTS</text>

    <text x="542" y="142" fill="${theme.accent}" font-size="24" font-weight="700">${levelHex}</text>
    <text x="542" y="161" fill="${theme.muted}" font-size="9"  font-weight="600" letter-spacing="2.2">LEVEL</text>
  </g>

  <line x1="172" y1="124" x2="172" y2="168" stroke="${theme.divider}" stroke-width="1"/>
  <line x1="320" y1="124" x2="320" y2="168" stroke="${theme.divider}" stroke-width="1"/>
  <line x1="468" y1="124" x2="468" y2="168" stroke="${theme.divider}" stroke-width="1"/>

  <text x="28" y="174" fill="${theme.muted}" fill-opacity="0.6" font-family="${FONT_MONO}" font-size="8" font-weight="500">theme · ${themeName}</text>
  <text x="612" y="174" fill="${theme.muted}" fill-opacity="0.6" font-family="${FONT_MONO}" font-size="8" font-weight="500" text-anchor="end">updated ${updatedAt}</text>
</svg>
`;
}

// TryHackMe's API is behind Vercel's bot mitigation: any request whose TLS/HTTP-2
// fingerprint is not a real browser gets a JS challenge (429, x-vercel-mitigated)
// instead of JSON — so a plain Node fetch is blocked. We delegate the fetch to a
// small Python helper using curl_cffi, which reproduces Chrome's exact handshake
// and is served the JSON directly. No headless browser, no challenge to solve.
function fetchProfileJson() {
  const fixture = process.env.THM_FIXTURE;
  if (fixture) {
    console.log(`[thm-badge] Using fixture ${fixture} (offline mode)`);
    return JSON.parse(fs.readFileSync(fixture, 'utf8'));
  }

  const helper = path.join(__dirname, 'fetch_profile.py');
  const python = process.env.PYTHON_BIN || 'python3';
  let stdout;
  try {
    stdout = execFileSync(python, [helper, USERNAME], {
      encoding: 'utf8',
      timeout: 90_000,
      maxBuffer: 16 * 1024 * 1024,
      stdio: ['ignore', 'pipe', 'inherit'],
    });
  } catch (err) {
    if (err.code === 'ENOENT') {
      throw new Error(`'${python}' not found — Python 3 with curl_cffi is required to fetch the profile.`);
    }
    throw new Error(`profile fetch failed (browser-TLS helper exited ${err.status ?? err.signal ?? 'error'})`);
  }
  return JSON.parse(stdout);
}

async function main() {
  const themeName = pickTheme(THEME_INPUT);
  const theme = { ...THEMES[themeName] };
  if (ACCENT_OVERRIDE) {
    theme.accent = ACCENT_OVERRIDE;
    theme.border = ACCENT_OVERRIDE;
  }
  console.log(`[thm-badge] Theme: ${themeName}${ACCENT_OVERRIDE ? ` (accent override: ${ACCENT_OVERRIDE})` : ''}`);
  console.log(`[thm-badge] Fetching profile for "${USERNAME}"...`);

  const json = fetchProfileJson();
  if (json.status !== 'success' || !json.data) {
    throw new Error(`Unexpected API payload: ${JSON.stringify(json).slice(0, 200)}`);
  }

  const svg = buildSvg(json.data, theme, themeName);
  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, svg, 'utf8');

  setOutput('theme_used', themeName);
  setOutput('rank', json.data.rank);

  console.log(`[thm-badge] Wrote ${OUTPUT_PATH}`);
  console.log(`[thm-badge] Stats: rank #${json.data.rank} · top ${json.data.topPercentage}% · ${json.data.completedRoomsNumber} rooms · ${json.data.badgesNumber} badges · level ${json.data.level} (${levelToHex(json.data.level)})`);
}

main().catch(err => {
  console.error('[thm-badge] FAILED:', err.message);
  process.exit(1);
});
